/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Syne", "sans-serif"],
        serif: ["Fraunces", "serif"],
        mono: ["DM Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "3px",
        sm: "2px",
        md: "3px",
      },
      colors: {
        bg: "var(--bg)",
        bg2: "var(--bg2)",
        ink: "var(--ink)",
        ink2: "var(--ink2)",
        ink3: "var(--ink3)",
        side: "var(--side)",
        amber: "var(--amber)",
        "amber-soft": "var(--amber-soft)",
        "amber-ink": "var(--amber-ink)",
        red: "var(--red)",
        "red-soft": "var(--red-soft)",
        green: "var(--green)",
        "green-soft": "var(--green-soft)",
        blue: "var(--blue)",
        "blue-soft": "var(--blue-soft)",
        card: "var(--card)",
        border: "var(--border)",
        border2: "var(--border2)",
        "run-title": "var(--run-banner-title)",
        "run-meta": "var(--run-banner-meta)",
        "on-dark-primary": "var(--on-dark-primary)",
        "on-dark-secondary": "var(--on-dark-secondary)",
        "on-dark-muted": "var(--on-dark-muted)",
        "on-dark-border": "var(--on-dark-border)",
        "on-dark-surface": "var(--on-dark-surface)",
        "on-dark-nav": "var(--on-dark-nav)",
        "on-dark-nav-hover": "var(--on-dark-nav-hover)",
        "on-dark-ghost": "var(--on-dark-ghost)",
        "on-dark-ghost-border": "var(--on-dark-ghost-border)",
        "on-dark-ghost-hover": "var(--on-dark-ghost-hover)",
        "on-dark-ghost-border-hover": "var(--on-dark-ghost-border-hover)",
      },
      boxShadow: {
        none: "none",
      },
    },
  },
  plugins: [],
};
